name: 'SkyWars'
version: ${project.version}
main: com.isnakebuzz.skywars.Main
authors: ['iSnakeBuzz_']
softdepend: ['FastAsyncWorldEdit', 'SnakeGameQueue', 'SnakeEconomy', 'ProtocolLib', 'PlaceholderAPI']
description: 'SkyWars Similar to HyPixel'
website: https://www.isnakebuzz.com/
commands:
  SkyWars:
    description: 'SkyWars principal command'
    aliases: ['sw', 'skyw', 'swars']