# Types: MYSQL
Type: MYSQL

# Tables
Tables:
  Player: 'SW_PLAYER'
  Solo: 'SW_SOLO_STATS'
  Team: 'SW_TEAM_STATS'

#Database
MySQL:
  enabled: false
  hostname: '127.0.0.1:3306'
  database: 'SkyWars'
  username: 'root'
  password: 'snake123'